// REST - stands for REpresentational State Transfer
// RESTful API - It is basically an API service that utilizes CRUD operations with HTTP requests 
// -- POST=CREATE, GET=READ, PUT=UPDATE, DELETE=DELETE
// -- The server will "expose" a bunch of services that are accessible via the HTTP protocal to certain endpoints
// -- The client (our API service) can then directly call these services by sending HTTP requests

//=====================================================================================================================
//=====================================================================================================================
// LOCALHOST

### Get all trainers
GET http://localhost:3000/trainers

### Get one trainer
GET http://localhost:3000/trainers/6349fd726b934afe1e97861d

### Create new trainer
POST http://localhost:3000/trainers
Content-Type: application/json

{
    "firstName": "Billy",
    "lastName": "Bob",
    "nickname": "Bug Catcher",
    "gymBadgesCollected": ["Boulder", "Cascade"],
    "pokemonCaught": 22
}

### Update a trainer
PUT http://localhost:3000/trainers/6351be87defae0e6b11e0e56
Content-Type: application/json

{
    "firstName": "Billy",
    "lastName": "Bob",
    "nickname": "Bug Catcher",
    "gymBadgesCollected": ["Boulder", "Cascade", "Rainbow"],
    "pokemonCaught": 45
}

### Delete a trainer
DELETE http://localhost:3000/trainers/6351be87defae0e6b11e0e56

//=====================================================================================================================

### Get all pokemon
GET http://localhost:3000/pokedex

### Get one pokemon
GET http://localhost:3000/pokedex/634a01ac6b934afe1e9eef87

### Create new pokemon
POST http://localhost:3000/pokedex
Content-Type: application/json

{
    "pokemonName": "Bulbasaur",
    "element": ["Grass", "Poison"],
    "abilities": ["Poison Powder", "Leech Seed", "Cut"],
    "healthPower": 45,
    "attack": 49,
    "defense": 49,
    "evolutions": ["Ivysaur", "Venusaur"]
}

### Update a pokemon
PUT http://localhost:3000/pokedex/6351c4ffbb749a413a32b500
Content-Type: application/json

{
    "pokemonName": "Ivysaur",
    "element": ["Grass", "Poison"],
    "abilities": ["Poison Powder", "Leech Seed", "Cut", "Skull Bash"],
    "healthPower": 65,
    "attack": 70,
    "defense": 68,
    "evolutions": ["Venusaur"]
}

### Delete a pokemon
DELETE http://localhost:3000/pokedex/6351c4ffbb749a413a32b500

//=====================================================================================================================
//=====================================================================================================================
// PRODUCTION

### Get all trainers
GET https://branden-cse341-pokemon.onrender.com/trainers

### Get one trainer
GET https://branden-cse341-pokemon.onrender.com/trainers/6349fd726b934afe1e97861d

### Create new trainer
POST https://branden-cse341-pokemon.onrender.com/trainers
Content-Type: application/json

{
    "firstName": "Billy",
    "lastName": "Bob",
    "nickname": "Bug Catcher",
    "gymBadgesCollected": ["Boulder", "Cascade"],
    "pokemonCaught": 22
}

### Update a trainer
PUT https://branden-cse341-pokemon.onrender.com/trainers/6351be87defae0e6b11e0e56
Content-Type: application/json

{
    "firstName": "Billy",
    "lastName": "Bob",
    "nickname": "Bug Catcher",
    "gymBadgesCollected": ["Boulder", "Cascade", "Rainbow"],
    "pokemonCaught": 45
}

### Delete a trainer
DELETE https://branden-cse341-pokemon.onrender.com/trainers/6351be87defae0e6b11e0e56

//=====================================================================================================================

### Get all pokemon
GET https://branden-cse341-pokemon.onrender.com/pokedex

### Get one pokemon
GET https://branden-cse341-pokemon.onrender.com/pokedex/634a01ac6b934afe1e9eef87

### Create new pokemon
POST https://branden-cse341-pokemon.onrender.com/pokedex
Content-Type: application/json

{
    "pokemonName": "Bulbasaur",
    "element": ["Grass", "Poison"],
    "abilities": ["Poison Powder", "Leech Seed", "Cut"],
    "healthPower": 45,
    "attack": 49,
    "defense": 49,
    "evolutions": ["Ivysaur", "Venusaur"]
}

### Update a pokemon
PUT https://branden-cse341-pokemon.onrender.com/pokedex/6351c4ffbb749a413a32b500
Content-Type: application/json

{
    "pokemonName": "Ivysaur",
    "element": ["Grass", "Poison"],
    "abilities": ["Poison Powder", "Leech Seed", "Cut", "Skull Bash"],
    "healthPower": 65,
    "attack": 70,
    "defense": 68,
    "evolutions": ["Venusaur"]
}

### Delete a pokemon
DELETE https://branden-cse341-pokemon.onrender.com/pokedex/6351c4ffbb749a413a32b500