// REST - stands for REpresentational State Transfer
// RESTful API - It is basically an API service that utilizes CRUD operations with HTTP requests 
// -- POST=CREATE, GET=READ, PUT=UPDATE, DELETE=DELETE
// -- The server will "expose" a bunch of services that are accessible via the HTTP protocal to certain endpoints
// -- The client (our API service) can then directly call these services by sending HTTP requests

//=====================================================================================================================
// LOCALHOST
//=====================================================================================================================

//=====================================================================================================================
// ---TRAINERS---

### Get all trainers
GET http://localhost:8080/trainers

### Get one trainer
GET http://localhost:8080/trainers/6349fd726b934afe1e97861d

### Create new trainer
POST http://localhost:8080/trainers
Content-Type: application/json

{
    "firstName": "Billy",
    "lastName": "Bob",
    "nickname": "Bug Catcher",
    "gymBadgesCollected": ["Boulder", "Cascade"],
    "pokemonCaught": 22
}

### Update a trainer
PUT http://localhost:8080/trainers/6351be87defae0e6b11e0e56
Content-Type: application/json

{
    "firstName": "Billy",
    "lastName": "Bob",
    "nickname": "Bug Catcher",
    "gymBadgesCollected": ["Boulder", "Cascade", "Rainbow"],
    "pokemonCaught": 45
}

### Delete a trainer
DELETE http://localhost:8080/trainers/6351be87defae0e6b11e0e56

//=====================================================================================================================
// ---POKEDEX---

### Get all pokemon
GET http://localhost:8080/pokedex

### Get one pokemon
GET http://localhost:8080/pokedex/634a01ac6b934afe1e9eef87

### Create new pokemon
POST http://localhost:8080/pokedex
Content-Type: application/json

{
    "pokemonName": "Bulbasaur",
    "elementType": ["Grass", "Poison"],
    "abilities": ["Poison Powder", "Leech Seed", "Cut"],
    "healthPower": 45,
    "attack": 49,
    "defense": 49,
    "evolutions": ["Ivysaur", "Venusaur"]
}

### Update a pokemon
PUT http://localhost:8080/pokedex/6351c4ffbb749a413a32b500
Content-Type: application/json

{
    "pokemonName": "Ivysaur",
    "elementType": ["Grass", "Poison"],
    "abilities": ["Poison Powder", "Leech Seed", "Cut", "Skull Bash"],
    "healthPower": 65,
    "attack": 70,
    "defense": 68,
    "evolutions": ["Venusaur"]
}

### Delete a pokemon
DELETE http://localhost:8080/pokedex/6351c4ffbb749a413a32b500

//=====================================================================================================================
// ---GYMS---

### Get all gyms
GET http://localhost:8080/gyms

### Get one gym
GET http://localhost:8080/gyms/6365dbca3ebf02caffa9f530

### Create new gym
POST http://localhost:8080/gyms
Content-Type: application/json

{
    "gymBadgeName": "Marsh Badge",
    "gymLocation": "Saffron City",
    "gymLeaderName": "Sabrina",
    "gymPokemonType": "Psychic"
}

### Update a gym
PUT http://localhost:8080/gyms/6365de8722f8b8c875d4cd73
Content-Type: application/json

{
    "gymBadgeName": "Volcano Badge",
    "gymLocation": "Cinnabar Island",
    "gymLeaderName": "Blaine",
    "gymPokemonType": "Fire"
}

### Delete a gym
DELETE http://localhost:8080/gyms/6365de8722f8b8c875d4cd73

//=====================================================================================================================
// ---GAMES---

### Get all games
GET http://localhost:8080/games

### Get one game
GET http://localhost:8080/games/6365dbca3ebf02caffa9f530

### Create new game
POST http://localhost:8080/games
Content-Type: application/json

{
    "gameName": "Pokemon Gold",
    "releaseDate": "10/15/2000",
    "platform": "Game Boy Color",
}

### Update a game
PUT http://localhost:8080/games/6365de8722f8b8c875d4c2a4
Content-Type: application/json

{
    "gameName": "Pokemon Crystal",
    "releaseDate": "07/29/2001",
    "platform": "Game Boy Color",
}

### Delete a game
DELETE http://localhost:8080/games/6365de8722f8b8c875d4c2a4



//=====================================================================================================================
// PRODUCTION
//=====================================================================================================================

//=====================================================================================================================
// ---TRAINERS---

### Get all trainers
GET https://branden-cse341-pokemon.onrender.com/trainers

### Get one trainer
GET https://branden-cse341-pokemon.onrender.com/trainers/6349fd726b934afe1e97861d

### Create new trainer
POST https://branden-cse341-pokemon.onrender.com/trainers
Content-Type: application/json

{
    "firstName": "Billy",
    "lastName": "Bob",
    "nickname": "Bug Catcher",
    "gymBadgesCollected": ["Boulder", "Cascade"],
    "pokemonCaught": 22
}

### Update a trainer
PUT https://branden-cse341-pokemon.onrender.com/trainers/6351be87defae0e6b11e0e56
Content-Type: application/json

{
    "firstName": "Billy",
    "lastName": "Bob",
    "nickname": "Bug Catcher",
    "gymBadgesCollected": ["Boulder", "Cascade", "Rainbow"],
    "pokemonCaught": 45
}

### Delete a trainer
DELETE https://branden-cse341-pokemon.onrender.com/trainers/6351be87defae0e6b11e0e56

//=====================================================================================================================
// ---POKEDEX---

### Get all pokemon
GET https://branden-cse341-pokemon.onrender.com/pokedex

### Get one pokemon
GET https://branden-cse341-pokemon.onrender.com/pokedex/634a01ac6b934afe1e9eef87

### Create new pokemon
POST https://branden-cse341-pokemon.onrender.com/pokedex
Content-Type: application/json

{
    "pokemonName": "Bulbasaur",
    "elementType": ["Grass", "Poison"],
    "abilities": ["Poison Powder", "Leech Seed", "Cut"],
    "healthPower": 45,
    "attack": 49,
    "defense": 49,
    "evolutions": ["Ivysaur", "Venusaur"]
}

### Update a pokemon
PUT https://branden-cse341-pokemon.onrender.com/pokedex/6351c4ffbb749a413a32b500
Content-Type: application/json

{
    "pokemonName": "Ivysaur",
    "elementType": ["Grass", "Poison"],
    "abilities": ["Poison Powder", "Leech Seed", "Cut", "Skull Bash"],
    "healthPower": 65,
    "attack": 70,
    "defense": 68,
    "evolutions": ["Venusaur"]
}

### Delete a pokemon
DELETE https://branden-cse341-pokemon.onrender.com/pokedex/6351c4ffbb749a413a32b500

//=====================================================================================================================
// ---GYMS---

### Get all gyms
GET https://branden-cse341-pokemon.onrender.com/gyms

### Get one gym
GET https://branden-cse341-pokemon.onrender.com/gyms/6365dbca3ebf02caffa9f530

### Create new gym
POST https://branden-cse341-pokemon.onrender.com/gyms
Content-Type: application/json

{
    "gymBadgeName": "Marsh Badge",
    "gymLocation": "Saffron City",
    "gymLeaderName": "Sabrina",
    "gymPokemonType": "Psychic"
}

### Update a gym
PUT https://branden-cse341-pokemon.onrender.com/gyms/6365de8722f8b8c875d4cd73
Content-Type: application/json

{
    "gymBadgeName": "Volcano Badge",
    "gymLocation": "Cinnabar Island",
    "gymLeaderName": "Blaine",
    "gymPokemonType": "Fire"
}

### Delete a gym
DELETE https://branden-cse341-pokemon.onrender.com/gyms/6365de8722f8b8c875d4cd73

//=====================================================================================================================
// ---GAMES---

### Get all games
GET https://branden-cse341-pokemon.onrender.com/games

### Get one game
GET https://branden-cse341-pokemon.onrender.com/games/6365dbca3ebf02caffa9f530

### Create new game
POST https://branden-cse341-pokemon.onrender.com/games
Content-Type: application/json

{
    "gameName": "Pokemon Gold",
    "releaseDate": "10/15/2000",
    "platform": "Game Boy Color",
}

### Update a game
PUT https://branden-cse341-pokemon.onrender.com/games/6365de8722f8b8c875d4c2a4
Content-Type: application/json

{
    "gameName": "Pokemon Crystal",
    "releaseDate": "07/29/2001",
    "platform": "Game Boy Color",
}

### Delete a game
DELETE https://branden-cse341-pokemon.onrender.com/games/6365de8722f8b8c875d4c2a4