// REST - stands for REpresentational State Transfer
// RESTful API - It is basically an API service that utilizes CRUD operations with HTTP requests 
// -- POST=CREATE, GET=READ, PUT=UPDATE, DELETE=DELETE
// -- The server will "expose" a bunch of services that are accessible via the HTTP protocal to certain endpoints
// -- The client (our API service) can then directly call these services by sending HTTP requests

//============================================================================================
// LOCALHOST

### Get all contacts
GET http://localhost:3000/contacts

### Get one contact by ID
GET http://localhost:3000/contacts/632b8ad92be31376f414f4ef

### Create new contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Pluto",
    "lastName": "Dog",
    "email": "pluto@stillaplanet.com",
    "favoriteColor": "Yellow",
    "birthday": "9/5/1935"
}

### Update contact
PUT http://localhost:3000/contacts/6335037808bd08de35ff0fff
Content-Type: application/json

{
    "firstName": "Super",
    "lastName": "Mario"
}

### Delete contact
DELETE http://localhost:3000/contacts/632b89222be31376f414f4ec


//============================================================================================
// PRODUCTION

### Get all contacts
GET https://branden-cse341-node.onrender.com/contacts

### Get one contact by ID
GET https://branden-cse341-node.onrender.com/contacts/632b8ad92be31376f414f4ef

### Create new contact
POST https://branden-cse341-node.onrender.com/contacts
Content-Type: application/json

{
    "firstName": "Goofy",
    "lastName": "Goof",
    "email": "goofy@gooftroop.com",
    "favoriteColor": "Orange",
    "birthday": "5/25/1932"
}

### Update contact
PUT https://branden-cse341-node.onrender.com/contacts/63361d857b3334bb3711c706
Content-Type: application/json

{
    "firstName": "Super",
    "lastName": "Mario"
}

### Delete contact
DELETE https://branden-cse341-node.onrender.com/contacts/63361d857b3334bb3711c706